
jobs:
  build:
    docker:
      - image: node:16.17.0
  
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --coverage

# version: 2.1
# orbs:
#   node: circleci/node@5.0.2
#   heroku: circleci/heroku@1.2.6

# jobs:
#   build_and_test:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           command: npm run test
#           name: Run tests
#       - run: server.test.js
#           command: npm run build
#           name: Build index.js
#       - persist_to_workspace:
#           root: ~/learn-express
#           paths:
#             - .

#   deploy: # this can be any name you choose
#     executor: heroku/default
#     steps:
#       - attach_workspace:
#           at: ~/learn-express
#       - heroku/deploy-via-git:
#           force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

# workflows:
#   test_my_app:
#     jobs:
#       - build_and_test
#       - deploy:
#           requires:
#             - build_and_test # only deploy if the build_and_test job has completed
#           filters:
#             branches:
#               only: ft-node-endpoints # only deploy when on main
