
# jobs:
#   build:
#     docker:
#       - image: node:18.13.0
  
#     steps:
#       - checkout:
#       - run:
#           name: Install dependencies
#           command: npm install
#       - run:
#           name: Run tests
#           command: npm test --coverage
         

version: 2.4

jobs:
  build:
    docker:
      - image: node:18.13.0
    environment:
      COVERALLS_REPO_TOKEN: 4Gyz2UxXVZy87gPU1thYWmwlEUo0TsawY
    working_directory: ~/mybrand/learn-express
    steps:
      - checkout:
          path: ~/mybrand
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --coverage -- --verbose
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info