name: Node.js CI

on:
  push:
    branches: [ft-node-endpoints]
  pull_request:
    branches: [ft-node-enpoints]

jobs:
  build:
    runs-on: ubuntu-latest
    # repo_token:4Gyz2UxXVZy87gPU1thYWmwlEUo0TsawY
    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test:coveralls
